### PR TITLE
Added SessionManager class with advanced session handling features

### LINKED ISSUE #234: [FEATURE] Add a static `SessionManager` class to Pancake
**Description:**
I would like to add a `SessionManager` class to the Pancake toolkit library in PHP. The class should act as a static wrapper around PHP's built-in session management functions, providing an easy-to-use interface for handling session operations. 

The `SessionManager` should handle tasks like starting sessions, setting, getting, and removing session data, and regenerating session IDs. The class will ensure that the session is started only when needed, reducing unnecessary overhead. Below is an example implementation:

```php
<?php

namespace GuiBranco\Pancake;

class SessionManager
{
    public static function start()
    {
        if (session_status() == PHP_SESSION_NONE) {
            session_start();
        }
    }

    public static function set($key, $value)
    {
        self::start();
        $_SESSION[$key] = $value;
    }

    public static function get($key, $default = null)
    {
        self::start();
        return $_SESSION[$key] ?? $default;
    }

    public static function has($key)
    {
        self::start();
        return isset($_SESSION[$key]);
    }

    public static function remove($key)
    {
        self::start();
        unset($_SESSION[$key]);
    }

    public static function destroy()
    {
        if (session_status() != PHP_SESSION_NONE) {
            session_unset();
            session_destroy();
        }
    }

    public static function regenerate()
    {
        if (session_status() != PHP_SESSION_NONE) {
            session_regenerate_id(true);
        }
    }
}
```

This class will provide a convenient interface for session handling and improve the Pancake library's overall functionality.

**Acceptance Criteria:**
- The `SessionManager` class is implemented and included in the Pancake toolkit.
- Unit tests are provided to ensure that the class behaves as expected.
- Documentation is updated to include usage examples of the `SessionManager`.

### PR DESCRIPTION
**Pull request by Humayun-23**
Closes #234

## 📑 Description

- Introduced session initialization with error handling for headers already sent.
- Added set(), get(), has(), and remove() methods for easy session variable management.
- Implemented session destruction and regeneration for improved security.
- Added flash() and getFlash() methods to handle temporary session data (flash data).
- Integrated session timeout handling via setExpiration() for session lifetime management.
- Optimized session locking by adding session_write_close() after writes.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] All the tests have passed

## ☢️ Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Introduced a `SessionManager` class for improved session management.
	- Added methods for starting sessions, setting and retrieving session variables, checking existence, removing variables, and destroying sessions.
	- Implemented flash message functionality for temporary notifications.
	- Added session expiration handling for enhanced security.
- **Documentation**
	- Comprehensive user guide added for the `SessionManager` class, detailing methods and usage examples.

### CODE REVIEW

**Comment by guibranco** [comment]
Hi @Humayun-23,

Thank you so much for your contribution! 🙌🚀 I appreciate your effort on this. 

I noticed that tests and documentation for this change are missing. Would you like to add those in a future commit, or is this PR ready for the final review? 🤔🔍

Looking forward to your thoughts! 😊

**Comment by Humayun-23** [comment]
I will be updatin the documentation in my next commit

**Comment by guibranco** [comment]
> I will be updating the documentation in my next commit. Do i have to put the documentation inside the code or do i have to create another documentation file?

The docs can be in the `/docs` directory, inside the [user-guide](https://github.com/guibranco/pancake/tree/main/docs/user-guide) directory. 
A file named `session-manager.md` will be enough. 

No need to add docs to the code itself!

Thanks,

**Comment by Humayun-23** [comment]
Added Documentation please check and review.  Specially the `has($key)` one

**Review by guibranco — APPROVED** [review]

**Comment by guibranco** [comment]
Hi @Humayun-23 ,

Thank you so much for your pull request! 🙌

I appreciate the time and effort you put into this contribution. 
I'll review it shortly, and if everything looks good, I'll approve it as soon as possible.

Thanks again for your valuable contribution! 🚀

**Comment by Humayun-23** [comment]
Thank you for considering my iputs valuable and merging the PR. I hope to contribute more in future. Thank you

**Pull request merged**
